### ISSUE TITLE
Addon started with errors

### ISSUE THREAD

**Issue by Burn-In** [MaxBec/hassio-diyHue#13]
Hi,
today morning after the bridge wasn't available anymore i did the last updates of HA and hassio-diyHue. But it wouldn't better.
At least i deinstalled the addon deleted the whole /config/diyhue folder, then installed the addon new.

The first install 3 weeks ago running true really easy.

What can i do? 

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: diyHue
 Philips Hue Bridge Emulator BETA
-----------------------------------------------------------
 Add-on version: 1.3.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.1.4
 Home Assistant Supervisor: 2021.01.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = BUILD_ARCH
Serve HTTPS
/opt/hue-emulator/functions/entertainment.py:97: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(nativeLights) is not 0:
/opt/hue-emulator/functions/entertainment.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(esphomeLights) is not 0:
/opt/hue-emulator/protocols/esphome.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if address["esphome_model"] is not "ESPHome-Toggle":
Host MAC given as XXXXXXXXXX
Docker Setup Initiated
SSL certificate found
Config file found
Docker Setup Complete
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 1991, in <module>
    initialize()
  File "/opt/hue-emulator/HueEmulator3.py", line 204, in initialize
    bridge_config["config"]["mac"] = mac[0] + mac[1] + ":" + mac[2] + mac[3] + ":" + mac[4] + mac[5] + ":" + mac[6] + mac[7] + ":" + mac[8] + mac[9] + ":" + mac[10] + mac[11]
IndexError: string index out of range
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------

**Comment by MaxBec** [comment]
Hey,
you have to supply a mac address in the add-on config.
