### ISSUE TITLE
installation error flask branch

### ISSUE THREAD

**Issue by juanesf** [MaxBec/hassio-diyHue#21]
Hi, I get the following error message when trying to install the diyhue flask branch

![imagen](https://user-images.githubusercontent.com/19717636/118156067-eb82cd00-b3e6-11eb-82de-eb05db24af07.png)

**Comment by HepoH3** [comment]
See: https://github.com/MaxBec/hassio-diyHue/issues/15
Actually, @MaxBec, the beta branch now has same dir strucrure as flusk, and there is a [fork of the beta branch](https://github.com/Thomas-86/diyHue/tree/beta) that [works with hue sync v1.6](https://diyhue.discourse.group/t/setting-up-hue-sync-app-pc-with-diyhue/240/10?u=hepoh), so it's will be really cool if this addon will support this structure.

**Comment by PDekker** [comment]
Hi @HepoH3 

I installed your fork to test the beta. There is no config.json created in the diyHue folder. The new ui looks nice, but there does not seem to be a option to configure Homeassistant access. Do you know what is going on?

**Comment by HepoH3** [comment]
> 
> 
> Hi @HepoH3
> 
> I installed your fork to test the beta. There is no config.json created in the diyHue folder. The new ui looks nice, but there does not seem to be a option to configure Homeassistant access. Do you know what is going on?

Indeed. Honestly, I use diyhue in order to set my yeelight bulb in music light mode with hue sync on PC, so I don't use hue integration on homeassistant. Don't really know why there is no config.json, I just fixed paths so beta branch will be able to install.

**Comment by PDekker** [comment]
> > Hi @HepoH3
> > I installed your fork to test the beta. There is no config.json created in the diyHue folder. The new ui looks nice, but there does not seem to be a option to configure Homeassistant access. Do you know what is going on?
> 
> Indeed. Honestly, I use diyhue in order to set my yeelight bulb in music light mode with hue sync on PC, so I don't use hue integration on homeassistant. Don't really know why there is no config.json, I just fixed paths so beta branch will be able to install.

Has a short chat on the diyhue slack. the config path changed from /opt/hue-emulator/export to /opt/hue-emulator/config

Can you please create a small change for this?

**Comment by HepoH3** [comment]
> 
> 
> > > Hi @HepoH3
> > > I installed your fork to test the beta. There is no config.json created in the diyHue folder. The new ui looks nice, but there does not seem to be a option to configure Homeassistant access. Do you know what is going on?
> > 
> > 
> > Indeed. Honestly, I use diyhue in order to set my yeelight bulb in music light mode with hue sync on PC, so I don't use hue integration on homeassistant. Don't really know why there is no config.json, I just fixed paths so beta branch will be able to install.
> 
> Had a short chat on the diyhue slack. the config path changed from /opt/hue-emulator/export to /opt/hue-emulator/config
> 
> Can you please create a small change for this?

I can't see any `export` word except exporting environment variables in file `run.sh`. I don't mind to implement this change, but I sincerely don't know where it needs to be implemented.

**Comment by MaxBec** [comment]
Closed #24
