### ISSUE TITLE
beta branch support

### ISSUE THREAD

**Issue by jameh** [MaxBec/hassio-diyHue#27]
thanks for this add-on, it's super convenient! (just sent you a tip!)

I am hoping to install the beta branch of diyhue in HA because of a fix for [this issue](https://github.com/diyhue/diyHue/issues/678). Are there plans to support installation of the beta branch with this add-on?

**Comment by MaxBec** [comment]
Thank you very much, James!

Maybe i can implement it right now. Will look how big the changes are.

**Comment by MaxBec** [comment]
So it is implemented now. Please have a look if it works :)

**Comment by jameh** [comment]
thank you! it seems to work for me
