### ISSUE TITLE
Alexa / Harmony unable to Pair

### ISSUE THREAD

**Issue by almostserious** [MaxBec/hassio-diyHue#6]
Hi, sorry for opening so many issues. 
Wondering if there maybe a better to way to discuss things like this in a forum thread instead.

However, when checking DIYHUE docs, it seems that Harmony Hub aswell as Alexa should be able to discover the diyhue since they both use the localapi. 

In my case however:

Alexa is not able to find my diyhue
harmony hub, while finding a hub, is not able to connect. 

Can I share any specific log output to help debugging this?

**Comment by MaxBec** [comment]
You just could use hassio for that. That's how i do it. So you have your main hub hassio and it is controlling everything. Nevertheless for diyhue specific issues please go to the diyhue repository and ask there. :)
