### ISSUE TITLE
Addon Not Installing - gzip: invalid magic

### ISSUE THREAD

**Issue by almostserious** [MaxBec/hassio-diyHue#7]
I encountered several issues, and decided to rebuild and then even to reinstall.
Now trying to install the addon I get the following logs:

```
(22/45) Installing mpc1 (1.1.0-r1)

(23/45) Installing gcc (9.3.0-r2)

(24/45) Installing musl-dev (1.1.24-r10)

(25/45) Installing libc-dev (0.7.2-r3)

(26/45) Installing g++ (9.3.0-r2)

(27/45) Installing make (4.3-r0)

(28/45) Installing fortify-headers (1.1-r0)

(29/45) Installing build-base (0.5-r2)

(30/45) Installing pcre2 (10.35-r0)

(31/45) Installing git (2.26.2-r0)

(32/45) Installing alpine-sdk (1.0-r0)

(33/45) Installing linux-headers (5.4.5-r1)

(34/45) Installing brotli-libs (1.0.9-r1)

(35/45) Installing c-ares (1.16.1-r0)

(36/45) Installing libuv (1.38.1-r0)

(37/45) Installing nodejs (12.18.4-r0)

(38/45) Installing npm (12.18.4-r0)

(39/45) Installing python2 (2.7.18-r0)

(40/45) Installing socat (1.7.3.4-r0)

(41/45) Installing udev-init-scripts (33-r1)

Executing udev-init-scripts-33-r1.post-install

(42/45) Installing eudev-libs (3.2.9-r3)

(43/45) Installing libblkid (2.35.2-r0)

(44/45) Installing kmod-libs (27-r0)

(45/45) Installing eudev (3.2.9-r3)

Executing busybox-1.31.1-r19.trigger

Executing eudev-3.2.9-r3.trigger

OK: 338 MiB in 87 packages

  % Total    % Received % Xferd  Average Speed   Tim
e    Time     Time  Curr
ent
       
           
             
  Dload  
Upload   To
tal   Spent
    Left
  Speed

  0     0   
 0     0  
  0     0  
    0      
0 --:--:-- 
--:--:-- -
-:--:--    
 0

  0     0    0
     0    0
     0      0      0 --:-
-:-- --:--:-- --:--:--    
 0
100   130  100   130  
  0     0    
522      0 
--:--:-- --
:--:-- --:--:-
-   520


100    14  100    14    0     0   
  33      0 --:--:-- -
-:--:-- --:
--:--    33

gzip: invalid magic

tar: Child returned status 1
tar: Error is not recoverable: exiting now

Removing intermediate container e727054318e1

```

As far as I am aware, nothing really changed to last my system from last time i was succesful in installing this addon.

**Comment by SidewalkPsycho** [comment]
`(12/44) Installing binutils (2.34-r1)
(13/44) Installing libmagic (5.38-r0)
(14/44) Installing file (5.38-r0)
(15/44) Installing gmp (6.2.0-r0)
(16/44) Installing isl (0.18-r0)
(17/44) Installing libgomp (9.3.0-r2)
(18/44) Installing libatomic (9.3.0-r2)
(19/44) Installing libgphobos (9.3.0-r2)
(20/44) Installing mpfr4 (4.0.2-r4)
(21/44) Installing mpc1 (1.1.0-r1)
(22/44) Installing gcc (9.3.0-r2)
(23/44) Installing musl-dev (1.1.24-r10)
(24/44) Installing libc-dev (0.7.2-r3)
(25/44) Installing g++ (9.3.0-r2)
(26/44) Installing make (4.3-r0)
(27/44) Installing fortify-headers (1.1-r0)
(28/44) Installing build-base (0.5-r2)
(29/44) Installing pcre2 (10.35-r0)
(30/44) Installing git (2.26.2-r0)
(31/44) Installing alpine-sdk (1.0-r0)
(32/44) Installing linux-headers (5.4.5-r1)
(33/44) Installing brotli-libs (1.0.9-r1)
(34/44) Installing c-ares (1.16.1-r0)
(35/44) Installing libuv (1.38.1-r0)
(36/44) Installing nodejs (12.18.4-r0)
(37/44) Installing npm (12.18.4-r0)
(38/44) Installing python2 (2.7.18-r0)
(39/44) Installing socat (1.7.3.4-r0)
(40/44) Installing udev-init-scripts (33-r1)
Executing udev-init-scripts-33-r1.post-install
(41/44) Installing eudev-libs (3.2.9-r3)
(42/44) Installing libblkid (2.35.2-r0)
(43/44) Installing kmod-libs (27-r0)
(44/44) Installing eudev (3.2.9-r3)
Executing busybox-1.31.1-r19.trigger
Executing eudev-3.2.9-r3.trigger
OK: 256 MiB in 87 packages
 
 %
 
Total    % Received % Xferd  Average Speed   Time    Time
     Time  Current
                                 Dload
  Upload   Total   Spent    Left 
 Speed


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100   130  100   130    0     0    339      0 --:--:-- --:--:-- --:--:--  
 339


100    14  100    14    0     0     17      0 --:--:-- --:--:-- --:--:--    17

gzip: invalid magic

tar: Child returned status 1
tar: Error is not recoverable: exiting now

Removing intermediate container a34ca2a3c724
`

Its the same for me.

**Comment by MaxBec** [comment]
Hey,

can you please check the bug with the new version? Thank you guys! :)

**Comment by almostserious** [comment]
It installed well with 1.3.2 as well as 1.4.0
