### ISSUE TITLE
update bridge needed

### ISSUE THREAD

**Issue by tomas8891** [MaxBec/hassio-diyHue#8]
When trying to make a new bridge it finds diyhue but then there is a screen that a update for the bridge is needed. 

When trying to install the bridge update it fails.

-EDIT Im not able to find config/diyhue in the folders to change the software version

-EDIT i now got the diyheu config from the github but in the config/json there is no software version to change.

**Comment by MaxBec** [comment]
Hey @tomas8891 ,

here you find the solution. Just change it under /config/diyhue/config.json.

**Comment by MaxBec** [comment]
https://diyhue.discourse.group/t/app-requires-update-of-hue-bridge-update-fails/233
